### PR TITLE
Fixing concurrent import problem

### PR DESCRIPTION
**Pull request by gogobd**
Fixing https://github.com/zopefoundation/Zope/issues/665
Thanks to https://github.com/d-maurer and https://github.com/iham for their help!

### CODE REVIEW

**Comment by jugmac00** [comment]
Usually, before merging into master, a PR gets reviewed by another contributor.

I don't know why this is enforced in some repositories, and not in others (like here maybe).

Also, every contributor has to sign a contributor agreement, see https://www.zope.org/developer/becoming-a-committer.html

(sorry, the above site seems to have a SSL cert issue (name mismatch)).

@dataflake @icemac @tseaver

**Comment by icemac** [comment]
At least an entry in the change log referencing the Zope issue would be nice.

**Comment by icemac** [comment]
Okay, maybe the entry for the previous commit covers this one two.

**Comment by tseaver** [comment]
@jugmac00 

> Usually, before merging into master, a PR gets reviewed by another contributor.

Yes, that is our current policy in all `zopefoundation` repositories.  Exceptions would be to deal with, e.g., reverting another PR which caused CI breakage, etc.  We don't enforce the review mechanically (using Github's branch protection mechanisms).

> Also, every contributor has to sign a contributor agreement,

If @gogobd hadn't signed it (long ago, in fact), he wouldn't have been on a team which allowed him to merge the PR.

**Comment by jugmac00** [comment]
@tseaver Thanks for claryfing.

**Pull request merged**
