### PR TITLE
Import StringIO from six

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by tseaver** [comment]
Would we be better off using `io.StringIO` and `io.BytesIO` (so that we enforced text-ness / bytes-ness as appropriate)?

**Comment by ale-rt** [comment]
My goal for the moment is to have the zope instance start with python 2 and python 3. 
StringIO and BytesIO are identical from six perspective under Python2.7:

- https://github.com/benjaminp/six/blob/master/six.py#L664

I meant to start watching  into some other tasks at a later stage.

Anyway if you have any pointer it would be great.

**Comment by tseaver** [comment]
@ale-rt

> StringIO and BytesIO are identical from six perspective under Python2.

f we don't "begin as we mean to go on" by clearly separating what uses of Python `str` are *meant* to be bytes vs. those which are really intended to be text, then there isn't much point in doing a port to Python3. We can use the standard library's `io.StringIO` and `io.BytesIO` in Python 2.7, which allows us to disentangle the two cases cleanly.

**Comment by ale-rt** [comment]
@tseaver I see your point.
It looks like I have to study a bit more to finalize this PR :p
I will try to get some inspiration from here: https://github.com/zopefoundation/zope.server/pull/3

For the moment thanks for the input, I will try to find some time to fix this patch :)

**Review by icemac — CHANGES_REQUESTED** [review]
As @tseaver suggested: Each import should be checked if text or bytes are actually needed.

**Comment by icemac** [comment]
@ale-rt Does it make sense to keep this PR open?

**Comment by ale-rt** [comment]
Nope, I totally forgot about it :)

**Pull request closed without merging**
